Lesson2
ok-technopolis-2021/Komissarov-Gleb pull request #2
Opened 2021-10-07 13:28 UTC by alltheshamefeelsthesame

Hw2

2021-10-22 21:31 UTC, aqus requested changes
1 ДЗ - 8.5 баллов, исправите соответственно замечаниям - балл может стать выше

2 ДЗ пока не могу принять, это совсем не то, что ожидалось, попробуйте следовать комментариям к ревью. Максимально близкое соответствие макету рекомендуется для получения максимального балла.

2021-10-22 21:31 UTC, aqus commented on Business-card/main/index.html
> +        <div class="circle"></div>
Это не просто какой-то круг, это фотография, для этого можно использовать тег image или класть изображение в background
Если следовать потоку документа, то фотография следует раньше, чем имя и специальность

2021-10-22 21:31 UTC, aqus commented on Business-card/styles/less2.css
> +.leftPart {
У документа есть какой-то поток следования блоков. Если это блочный контекст форматирования - то блоки следуют друг за другом сверху вниз. Если строчный контекст форматирования - слева на право (справа на лево в случае иврита)

Попробуйте стилизовать документ с учетом этих знаний без position: absolute и ограничения элементов по ширине и высоте.
Позвольте элементам быть размером с их контент и будьте готовы к тому, что контент будет больше ожидаемого, то есть предполагается, что блок будет растягиваться по размеру его контента.
Регулируйте внутренние отступы через padding, а внешние через margin - этого почти всегда достаточно, чтобы следовать макету.

Старайтесь стилизовать максимально близко к макету, сейчас и близко не похоже на макет.

2021-11-09 21:46 UTC, aqus approved these changes
2 ДЗ - 8,5 баллов, есть некоторые несоответствия макету
![image](https://user-images.githubusercontent.com/5273083/141009846-05eb9bdd-1d2f-4c1b-a68f-0ea1b9194763.png)

2021-11-09 21:46 UTC, aqus commented on Business-card/styles/style.css
> +.telegram, .github, .spotify {
можно было бы использовать какой-нибудь один абстрактный класс

2021-11-09 21:46 UTC, aqus commented on Business-card/styles/style.css
> +  height: 180px;
если фото будет квадратным, то будет все хорошо, если использовать прямоугольное фото, то исказятся пропорции поэтому для таких случаев лучше фиксировать только одну сторону или класть фото в background в блок

2021-11-10 07:26 UTC, closed without merging

2021-11-10 07:26 UTC, alltheshamefeelsthesame commented
Merged3